name: 'Tests'

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create firebasekey.json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "firebasekey.json"
          json: ${{ secrets.FIREBASE_KEY }}
          
      # - name: Build, Push and Deploy to Heroku
      #   id: heroku
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
      #     usedocker: True
      #     stack: container
