name: 'Tests'

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          HEROKU_APP_NAME = ${{ secrets.HEROKU_TEST_APP_NAME }}

      - name: Create firebasekey.json
        uses: jsdaniell/create-json@1.1.2
        if: github.ref == 'refs/head/main'
        env:
          HEROKU_APP_NAME = ${{ secrets.HEROKU_APP_NAME }}
        with:
          name: "firebasekey.json"
          json: ${{ secrets.FIREBASE_KEY }}
          
      # If main, HEROKU_APP_NAME else HEROKU_TEST_APP_NAME
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          usedocker: True
          stack: container
